apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  labels:
    app: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: homarr
        image: ghcr.io/homarr-labs/homarr:latest
        env:
        - name: SECRET_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: homarr-secrets
              key: SECRET_ENCRYPTION_KEY
        ports:
        - containerPort: 7575
          name: http
        volumeMounts:
        - name: homarr-configs
          mountPath: /app/data/configs
        - name: homarr-data
          mountPath: /app/data
      volumes:
      - name: homarr-configs
        emptyDir: {}
      - name: homarr-data
        emptyDir: {}
