apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage # Força o mesmo nome usado no PVC automático do Vault
  local:
    path: /mnt/storage/vault # Pasta física no nó
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NOME_DO_SEU_NO # Coloque o nome do nó onde a pasta foi criada