server:
  dev:
    enabled: false

 
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: "local-storage"

  
  service:
    type: NodePort
    nodePort: 30082

  
  securityContext:
    runAsUser: 100
    runAsGroup: 1000
    fsGroup: 1000


  ui:
    enabled: true